title: Team Project of EPPS 6302
description: This website is for group project in [EPPS 6302] Method of Data Collection & Production (2025 Fall)
url: "https://solb-kim.github.io/EPPS6302team"      
baseurl:             

avatar: /assets/img/logo.jpg
paginate: 5
permalink: pretty
cover_image: /assets/img/box.jpg
timezone: America/Chicago


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
      sidebar: custom_sidebar


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

include:
  - _pages
  
# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - scripts/


sass:
  sass_dir: _sass
  style: :compressed




# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: UA-179353572-1

# Replace this value and uncomment to enable Disqus
disqus: vszhub

remote_theme: vszhub/not-pure-poole
